# Generated by Django 6.0.2 on 2026-02-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studycore', '0002_subject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
