# Generated by Django 6.0.2 on 2026-02-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studycore', '0003_chatmessage_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='citations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
